#!/bin/bash
# ============================================
# PrintServer Pro — Docker Migration Import
# Jalankan di SERVER BARU
# Prasyarat: /tmp/printserver-migration.tar.gz sudah ada
# ============================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log() { echo -e "${BLUE}[$(date '+%H:%M:%S')]${NC} $1"; }
ok()  { echo -e "${GREEN}  ✓${NC} $1"; }
warn(){ echo -e "${YELLOW}  ⚠${NC} $1"; }
die() { echo -e "${RED}  ✗ $1${NC}"; exit 1; }

ARCHIVE="/tmp/printserver-migration.tar.gz"
WORK_DIR="/tmp/printserver-import-$$"
PROJECT_DIR="/opt/printserver"
COMPOSE_DIR="$PROJECT_DIR/docker"

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}  PrintServer Pro — Docker Migration Import${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

# ── Preflight ───────────────────────────────────────────────────────────────
[ ! -f "$ARCHIVE" ] && die "Archive tidak ditemukan: $ARCHIVE\n  Jalankan di server lama: bash scripts/migrate-export.sh\n  Lalu: scp /tmp/printserver-migration.tar.gz root@<BARU>:/tmp/"

# Detect IP
SERVER_IP=$(hostname -I | awk '{print $1}')
echo -e "  Server IP detected: ${YELLOW}$SERVER_IP${NC}"
echo ""

# ── 1. Install dependensi ──────────────────────────────────────────────────
log "[1/8] Installing system dependencies..."

# Docker
if ! command -v docker &>/dev/null; then
    curl -fsSL https://get.docker.com | sh
    ok "Docker installed: $(docker --version | head -1)"
else
    ok "Docker: $(docker --version | head -1)"
fi

# Docker Compose
if docker compose version &>/dev/null; then
    ok "Docker Compose: $(docker compose version --short)"
elif docker-compose --version &>/dev/null; then
    ok "Docker Compose (legacy): $(docker-compose --version)"
else
    die "Docker Compose tidak ditemukan"
fi

# PM2 (for local process management if needed)
if ! command -v pm2 &>/dev/null; then
    npm install -g pm2 2>/dev/null && ok "PM2 installed" || warn "PM2 install skipped"
fi

# ── 2. Clone project ──────────────────────────────────────────────────────
log "[2/8] Cloning project..."
if [ -d "$PROJECT_DIR/.git" ]; then
    cd "$PROJECT_DIR" && git pull origin main 2>/dev/null && ok "Project updated" || ok "Project exists, using current"
else
    git clone https://github.com/BAYU18/sprin.git "$PROJECT_DIR" && ok "Project cloned"
fi
cd "$PROJECT_DIR"

# ── 3. Extract migration data ─────────────────────────────────────────────
log "[3/8] Extracting migration data..."
mkdir -p "$WORK_DIR"
tar -xzf "$ARCHIVE" -C "$WORK_DIR"
ok "Archive extracted"

# ── 4. Create Docker .env ─────────────────────────────────────────────────
log "[4/8] Creating Docker .env..."

# Read secrets from old server's .env
OLD_ENV="$WORK_DIR/configs/server.env"
if [ -f "$OLD_ENV" ]; then
    OLD_JWT=$(grep -oP 'JWT_SECRET=\K.*' "$OLD_ENV" 2>/dev/null || echo "")
    OLD_CLIENT_SECRET=$(grep -oP 'CLIENT_SECRET=\K.*' "$OLD_ENV" 2>/dev/null || echo "")
    OLD_NODE_SECRET=$(grep -oP 'NODE_SECRET=\K.*' "$OLD_ENV" 2>/dev/null || echo "")
else
    OLD_JWT=""
    OLD_CLIENT_SECRET=""
    OLD_NODE_SECRET=""
fi

# Generate secrets if not found
JWT_SECRET="${OLD_JWT:-$(openssl rand -hex 32)}"
CLIENT_SECRET="${OLD_CLIENT_SECRET:-$(openssl rand -hex 16)}"
NODE_SECRET="${OLD_NODE_SECRET:-$(openssl rand -hex 16)}"
DB_PASSWORD="prints3rv3r2024"
REDIS_PASSWORD="redis-prints3rv3r"

cat > "$COMPOSE_DIR/.env" << ENVEOF
# PrintServer Pro — Docker Environment
# Generated by migrate-import.sh on $(date -Iseconds)

# Database
DB_USER=printserver
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=printserver

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# Server
SERVER_IP=${SERVER_IP}
SERVER_NAME=PrintServer
API_PUBLIC_URL=http://${SERVER_IP}:3000
WS_PUBLIC_URL=ws://${SERVER_IP}:3000

# Secrets (restored from old server or auto-generated)
JWT_SECRET=${JWT_SECRET}
CLIENT_SECRET=${CLIENT_SECRET}
NODE_SECRET=${NODE_SECRET}
ENVEOF

ok ".env created (IP: $SERVER_IP)"
echo ""

# ── 5. Build Docker images ────────────────────────────────────────────────
log "[5/8] Building Docker images (this may take a few minutes)..."
cd "$COMPOSE_DIR"

# Build API image (multi-stage: tsc + production)
docker compose build --no-cache api 2>&1 | tail -5
ok "API image built"

# Build Dashboard image (multi-stage: next build + standalone)
docker compose build --no-cache dashboard 2>&1 | tail -5
ok "Dashboard image built"

# ── 6. Start database & restore ───────────────────────────────────────────
log "[6/8] Starting database & restoring data..."

# Start only postgres first
docker compose up -d postgres
echo "  Waiting for PostgreSQL..."
for i in $(seq 1 30); do
    if docker compose exec -T postgres pg_isready -U printserver &>/dev/null; then
        ok "PostgreSQL ready"
        break
    fi
    [ $i -eq 30 ] && die "PostgreSQL not ready after 90s"
    sleep 3
done

# Restore database
SQL_FILE="$WORK_DIR/db/printserver.sql"
if [ -f "$SQL_FILE" ] && [ -s "$SQL_FILE" ]; then
    log "  Restoring database..."
    # Create database if not exists
    docker compose exec -T postgres psql -U printserver -d postgres -c "CREATE DATABASE printserver OWNER printserver;" 2>/dev/null || true
    # Restore
    docker compose exec -T -T postgres psql -U printserver -d printserver < "$SQL_FILE" 2>/dev/null
    ok "Database restored ($(du -h "$SQL_FILE" | cut -f1))"
else
    warn "No database dump found — starting with fresh DB"
fi

# Start Redis
docker compose up -d redis
ok "Redis started"

# ── 7. Start API & Dashboard ─────────────────────────────────────────────
log "[7/8] Starting API & Dashboard..."
docker compose up -d api
echo "  Waiting for API..."
for i in $(seq 1 30); do
    if docker compose exec -T api wget -q --spider http://localhost:3000/health 2>/dev/null; then
        ok "API healthy"
        break
    fi
    [ $i -eq 30 ] && warn "API health check timeout (may still be starting)"
    sleep 3
done

docker compose up -d dashboard
ok "Dashboard started"

# ── 8. Restore downloads & config ────────────────────────────────────────
log "[8/8] Restoring files..."

# Downloads (agent .bat files, APK, etc.)
if [ -d "$WORK_DIR/downloads" ] && [ "$(ls -A "$WORK_DIR/downloads" 2>/dev/null)" ]; then
    mkdir -p "$PROJECT_DIR/apps/server/public/downloads"
    cp -r "$WORK_DIR/downloads/"* "$PROJECT_DIR/apps/server/public/downloads/" 2>/dev/null
    ok "Downloads restored"
fi

# Copy cloudflared tunnel setup
if command -v cloudflared &>/dev/null; then
    ok "cloudflared available"
else
    warn "cloudflared not installed — run: wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared && chmod +x /usr/local/bin/cloudflared"
fi

# Cleanup
rm -rf "$WORK_DIR"

# ── Summary ──────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  MIGRATION COMPLETE!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo -e "  ${GREEN}Dashboard:${NC}  http://${SERVER_IP}:3001"
echo -e "  ${GREEN}API:${NC}         http://${SERVER_IP}:3000/api/health"
echo -e "  ${GREEN}Login:${NC}       admin / changeme123"
echo ""
echo -e "  ${YELLOW}Node agents:${NC}"
echo -e "  Update serverUrl di config agent ke: http://${SERVER_IP}:3000"
echo -e "  Agent v1.4.4+ otomatis kirim IP asli via ipconfig"
echo ""
echo -e "  ${YELLOW}Cloudflare Tunnel:${NC}"
echo -e "  cloudflared tunnel --url http://localhost:3001"
echo ""
echo -e "  ${YELLOW}Useful commands:${NC}"
echo -e "  cd $COMPOSE_DIR"
echo -e "  docker compose ps          # cek status"
echo -e "  docker compose logs -f     # cek logs"
echo -e "  docker compose restart     # restart semua"
echo -e "  docker compose down        # stop semua"
echo ""
echo -e "  ${BLUE}PM2 alternative (non-Docker):${NC}"
echo -e "  cd $PROJECT_DIR && bash scripts/start.sh"
echo ""
