/**
 * Auto-update module for PrintServer Node Agent
 *
 * Strategy: every 30 minutes, the running agent asks the server
 *   GET {serverUrl}/downloads/agent/info
 * and compares `version` + `buildTime` against its own baked-in
 * CURRENT_VERSION. When the server reports a newer build, the agent
 * downloads a fresh copy to <current>.exe.new and hands the swap
 * off to a small PowerShell bootstrap so the file can be safely
 * replaced (Windows won't let you overwrite a running PE).
 *
 * The bootstrap (updater-bootstrap.ps1) is generated on the fly into
 * %TEMP%\printserver-updater.ps1 and:
 *   1. Waits 3 seconds for the parent agent to exit.
 *   2. Moves <current>.exe.new -> <current>.exe (overwrite).
 *   3. Spawns the new exe.
 *   4. Deletes itself.
 *
 * No user interaction, no admin required for the swap (file is in
 * %APPDATA% which the user owns).
 */

const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawn } = require('child_process');

const CURRENT_VERSION = '1.2.1';
const UPDATE_CHECK_INTERVAL = 30 * 60 * 1000; // 30 minutes
const INITIAL_CHECK_DELAY = 60 * 1000;        // wait 1 min after startup

// Files below %APPDATA%\printserver-agent\  (created by installer)
function getInstallDir() {
  const appData = process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming');
  return path.join(appData, 'printserver-agent');
}
function getExePath() {
  return process.execPath; // pkg-built exe is its own execPath
}
function getNewExePath() {
  return getExePath() + '.new';
}
function getBootstrapPath() {
  return path.join(os.tmpdir(), 'printserver-updater.ps1');
}

const BOOTSTRAP_TEMPLATE = `
# Auto-generated by PrintServer Agent updater — do not edit
$ErrorActionPreference = 'Stop'
$exe    = $args[0]
$newExe = $args[1]

Write-Host "[updater] Sleeping 3s for parent agent to exit..."
Start-Sleep -Seconds 3

# On Windows, a running exe holds an exclusive write lock. Retry the
# move a few times in case some AV or spooler is briefly holding it.
$ok = $false
for ($i = 1; $i -le 10; $i++) {
  try {
    if (Test-Path $exe) { Remove-Item $exe -Force }
    Move-Item $newExe $exe -Force
    $ok = $true
    break
  } catch {
    Write-Host "[updater] Move attempt $i failed: $($_.Exception.Message)"
    Start-Sleep -Seconds 2
  }
}

if (-not $ok) {
  Write-Host "[updater] FAILED to swap binary after 10 attempts"
  exit 1
}

Write-Host "[updater] Swap complete. Checking service status..."
$serviceName = "PrintServerAgent"
$service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
if ($service) {
  Write-Host "[updater] Detected Windows Service. Restarting $serviceName..."
  Restart-Service -Name $serviceName -Force
} else {
  Write-Host "[updater] Running in desktop mode. Relaunching $exe"
  Start-Process -FilePath $exe
}

Write-Host "[updater] Done. Self-removing in 5s..."
Start-Sleep -Seconds 5
Remove-Item $PSCommandPath -Force -ErrorAction SilentlyContinue
`;

class AutoUpdater {
  constructor({ serverUrl, log }) {
    this.serverUrl = (serverUrl || '').replace(/\/$/, '');
    this.log = log || (() => {});
    this.timer = null;
    this.inProgress = false;
  }

  start() {
    if (!this.serverUrl) {
      this.log('warn', '[Updater] serverUrl not set, auto-update disabled');
      return;
    }
    if (process.pkg === undefined) {
      // Running unpackaged (node src/index.js) — skip update, would just
      // overwrite dev sources.
      this.log('info', '[Updater] Running unpackaged, auto-update disabled');
      return;
    }
    this.log('info', `[Updater] Auto-update enabled (current v${CURRENT_VERSION}, check every ${UPDATE_CHECK_INTERVAL/60000} min)`);
    setTimeout(() => this.check(), INITIAL_CHECK_DELAY);
    this.timer = setInterval(() => this.check(), UPDATE_CHECK_INTERVAL);
  }

  stop() {
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
  }

  async check() {
    if (this.inProgress) return;
    this.inProgress = true;
    try {
      const infoUrl = this.serverUrl + '/downloads/agent/info';
      const ctrl = new AbortController();
      const timeout = setTimeout(() => ctrl.abort(), 15000);
      const resp = await fetch(infoUrl, { signal: ctrl.signal });
      clearTimeout(timeout);
      if (!resp.ok) {
        this.log('warn', `[Updater] info fetch failed: HTTP ${resp.status}`);
        return;
      }
      const info = await resp.json();
      this.log('debug', '[Updater] server info', info);

      if (!info.version || !info.downloadUrl) {
        this.log('warn', '[Updater] server returned incomplete info, skipping');
        return;
      }

      if (info.version === CURRENT_VERSION) {
        this.log('debug', '[Updater] already up to date');
        return;
      }

      this.log('info', `[Updater] Update available: v${CURRENT_VERSION} -> v${info.version} (size ${info.size} bytes)`);
      await this.downloadAndApply(info);
    } catch (err) {
      this.log('warn', `[Updater] check failed: ${err.message}`);
    } finally {
      this.inProgress = false;
    }
  }

  async downloadAndApply(info) {
    const exePath = getExePath();
    const newExePath = getNewExePath();
    const bootstrap = getBootstrapPath();
    const downloadUrl = this.serverUrl + info.downloadUrl;

    this.log('info', `[Updater] Downloading ${downloadUrl} -> ${newExePath}`);
    const ctrl = new AbortController();
    const timeout = setTimeout(() => ctrl.abort(), 5 * 60 * 1000); // 5min for 42MB
    const resp = await fetch(downloadUrl, { signal: ctrl.signal });
    clearTimeout(timeout);
    if (!resp.ok) throw new Error(`download HTTP ${resp.status}`);

    const total = parseInt(resp.headers.get('content-length') || info.size || '0', 10);
    const file = fs.createWriteStream(newExePath);
    let downloaded = 0;
    const reader = resp.body.getReader();
    try {
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        file.write(Buffer.from(value));
        downloaded += value.length;
        if (total && downloaded % (5 * 1024 * 1024) < value.length) {
          this.log('debug', `[Updater] ${(downloaded/1024/1024).toFixed(1)} / ${(total/1024/1024).toFixed(1)} MB`);
        }
      }
    } finally {
      reader.releaseLock();
    }
    await new Promise((res, rej) => {
      file.end((err) => err ? rej(err) : res());
    });

    if (total && downloaded !== total) {
      fs.unlinkSync(newExePath);
      throw new Error(`size mismatch: got ${downloaded}, expected ${total}`);
    }

    // Write bootstrap script
    fs.writeFileSync(bootstrap, BOOTSTRAP_TEMPLATE);

    this.log('info', '[Updater] Spawning swap bootstrap, exiting in 2s...');
    spawn('powershell.exe', [
      '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass',
      '-File', bootstrap,
      exePath, newExePath
    ], {
      detached: true,
      stdio: 'ignore',
      windowsHide: true
    }).unref();

    // Give bootstrap 2s to attach, then exit so it can move the file
    setTimeout(() => {
      this.log('info', '[Updater] Exiting for swap. Will auto-relaunch as v' + info.version);
      process.exit(0);
    }, 2000);
  }
}

module.exports = { AutoUpdater, CURRENT_VERSION };
